### ISSUE TITLE
creators page http Status Error 500

### ISSUE THREAD

**Issue by vmario89** [manyfold3d/manyfold#3304]
**Describe the bug**
In version 0.90.2 and recent 0.91.1 i cannot access the /creators page, as it throws error. The log output is not precise enough for me to understand what/why this happens

**To Reproduce**
go to https://hardware.fab-access.org/creators

**Expected behavior**
The page should load

**Screenshots**
![grafik](https://github.com/user-attachments/assets/3d77ccd1-33de-4bef-906a-03c65687f3bd)

**Desktop (please complete the following information):**
 - Browser: tried different: firefox, chrome, ...

**Additional context**
Log Output:

```
[app]             | 22:25:58 rails.1              | I, [2024-12-11T22:25:58.401392 #153]  INFO -- : [3904931a-e14d-48f1-88c5-77f12825cee6] {"method":"GET","path":"/creators","format":"html","controller":"CreatorsController","action":"index","status":500,"allocations":10573,"duration":17.48,"view":0.0,"db":3.36,"@timestamp":"2024-12-11T22:25:58.401Z","@version":"1","message":"[500] GET /creators (CreatorsController#index)"}
[app]             | 22:25:58 rails.1              | F, [2024-12-11T22:25:58.402993 #153] FATAL -- : [3904931a-e14d-48f1-88c5-77f12825cee6]   
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] ActionView::Template::Error (Name is blank):
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] 
[app]             | 22:25:58 rails.1              | Causes:
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] PublicSuffix::DomainInvalid (Name is blank)
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]      7:       <% end %>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]      8:       <ul class='links'>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]      9:         <% creator.links.each do |link| %>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]     10:           <li><%= link_to t("sites.%{site}" % {site: link.site}), link.url %></li>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]     11:         <% end %>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]     12:       </ul>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]     13:       <%= link_to "#{policy_scope(Model).where(creator: creator).count} #{Model.model_name.human count: policy_scope(Model).where(creator: creator).count}", creator, {class: "btn btn-primary", "aria-label": translate(".models_button.label", name: creator.name)} if policy(creator).show? %>
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6]   
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/models/link.rb:9:in `site'
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/views/creators/_creator.html.erb:10
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/views/creators/_creator.html.erb:9
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/views/creators/index.html.erb:12
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/views/creators/index.html.erb:1
[app]             | 22:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/controllers/creators_controller.rb:31:in `index'
[app]             | 2
```2:25:58 rails.1              | [3904931a-e14d-48f1-88c5-77f12825cee6] app/controllers/application_controller.rb:86:in `switch_locale'

**Comment by Floppy** [comment]
It looks like there's an error with a URL in one of the creators, perhaps a new bit of code is validating it in a way that it wasn't before. It's not https://hardware.fab-access.org/creators/joris-bijkerk; do you have any other public creators that it might be? If you can find one, view its individual creator page and check for URLs, then perhaps try removing it in edit, or see if it fails validation if you save the creator details.

**Comment by Floppy** [comment]
I should also do a fix so that that the Link#site method fails safe, rather than causing an exception.

**Comment by Floppy** [comment]
OK, I've put in a code fix and test for this, so the next release should fix it. You can either swap to `edge` for now, or I will do a patch release before the end of the day with anything else that comes up as well.

**Comment by vmario89** [comment]
Hi @Floppy thank you for the commit! I tried to run the patched version. It changed to the following error now. It seems to have also something to do with the locale:

```
19:38:05 rails.1              | I, [2024-12-12T19:38:05.065574 #150]  INFO -- : [339ed0ed-6b74-4470-824e-cf6f3765d91e] {"method":"GET","path":"/creators","format":"html","controller":"CreatorsController","action":"index","status":500,"allocations":10627,"duration":26.8,"view":0.0,"db":3.42,"@timestamp":"2024-12-12T19:38:05.065Z","@version":"1","message":"[500] GET /creators (CreatorsController#index)"}
19:38:05 rails.1              | F, [2024-12-12T19:38:05.067709 #150] FATAL -- : [339ed0ed-6b74-4470-824e-cf6f3765d91e]   
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] ActionView::Template::Error (undefined method `locale' for an instance of Hash):
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] 
19:38:05 rails.1              | Causes:
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] NoMethodError (undefined method `locale' for an instance of Hash)
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]      7:       <% end %>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]      8:       <ul class='links'>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]      9:         <% creator.links.each do |link| %>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]     10:           <li><%= link_to t("sites.%{site}" % {site: link.site}), link.url %></li>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]     11:         <% end %>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]     12:       </ul>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]     13:       <%= link_to "#{policy_scope(Model).where(creator: creator).count} #{Model.model_name.human count: policy_scope(Model).where(creator: creator).count}", creator, {class: "btn btn-primary", "aria-label": translate(".models_button.label", name: creator.name)} if policy(creator).show? %>
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e]   
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/helpers/application_helper.rb:170:in `block in translate_with_locale_wrapper'
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/helpers/application_helper.rb:169:in `translate_with_locale_wrapper'
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/views/creators/_creator.html.erb:10
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/views/creators/_creator.html.erb:9
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/views/creators/index.html.erb:12
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/views/creators/index.html.erb:1
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/controllers/creators_controller.rb:31:in `index'
19:38:05 rails.1              | [339ed0ed-6b74-4470-824e-cf6f3765d91e] app/controllers/application_controller.rb:86:in `switch_locale'

```

**Comment by Floppy** [comment]
Oh! That's weird, let me take another look at it then.

**Comment by Floppy** [comment]
I can't replicate that error here, it's probably to do with the specific link you've got. Did you manage to work out what it is?

**Comment by vmario89** [comment]
no i was not able to find the problem yet. i tried different languages but it always appears

the instance hardware.fab-access.org has only two authors a.t.m. so i dont catch the point :/

i also tried to check if its an url problem but same error on both:
```
https://hardware.fab-access.org/creators/
https://hardware.fab-access.org/creators
```

i think it dont has to do sth. with nginx:
on minimal setup everything is fine except the creators page
```
    location / {
        proxy_pass http://127.0.0.1:3214;
    }
```

**Comment by Floppy** [comment]
I don't think so... but it's just occurred to me that it could indeed be a locale thing - presumably you're using German? Does it happen if you force English?

**Comment by Floppy** [comment]
Actually, no, it does the same for me, and I'm looking at it in English. And when I force my instance into German, it doesn't break. OK, not that.

**Comment by Floppy** [comment]
One more thing to try. Does it work if you just *remove* the URLs from the creators?

**Comment by vmario89** [comment]
no i removed them right now, but it doesnt change anything. i also played with visibility of the users

**Comment by Floppy** [comment]
Hm, OK, that's a distraction then. I'll dig deeper.

**Comment by Floppy** [comment]
OK, I've managed to replicate it - there's definitely a bad (or somehow empty) link in there somewhere, but I will make the code more defensive to stop it in its tracks.

**Comment by Floppy** [comment]
Right, think I've fixed it. If you're able to try the `edge` image, could you give it a go?

**Comment by Floppy** [comment]
Fix is also in v0.91.3, now released.

**Comment by vmario89** [comment]
hi @Floppy , thank you really much for your investigation! I updated to recent 0.91.3 but it still not gone :-O

**Comment by vmario89** [comment]
after deleting empty links it works! but thats maybe not the fix

**Comment by Floppy** [comment]
it should handle empty links safely now anyway, so I think it's double-fixed. Glad it's working for you!
